"""empty message

Revision ID: c61c6ccd0af0
Revises: b46c5b1470c6
Create Date: 2023-05-15 15:54:35.683748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61c6ccd0af0'
down_revision = 'b46c5b1470c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_applications',
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('client_type', sa.String(length=32), nullable=True),
    sa.Column('authorization_grant_type', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('algorithm', sa.String(length=5), nullable=True),
    sa.Column('redirect_uris', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC время создания'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC время обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth2_applications_client_id'), 'oauth2_applications', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth2_applications_client_secret'), 'oauth2_applications', ['client_secret'], unique=False)
    op.drop_index('ix_applications_client_id', table_name='applications')
    op.drop_index('ix_applications_client_secret', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('client_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('client_secret', sa.VARCHAR(length=255), nullable=True),
    sa.Column('client_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('authorization_grant_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('algorithm', sa.VARCHAR(length=5), nullable=True),
    sa.Column('redirect_uris', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('create_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_client_secret', 'applications', ['client_secret'], unique=False)
    op.create_index('ix_applications_client_id', 'applications', ['client_id'], unique=False)
    op.drop_index(op.f('ix_oauth2_applications_client_secret'), table_name='oauth2_applications')
    op.drop_index(op.f('ix_oauth2_applications_client_id'), table_name='oauth2_applications')
    op.drop_table('oauth2_applications')
    # ### end Alembic commands ###
